/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractProcessScopeProvider extends DelegatingScopeProvider {
}
