/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actor Category</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.ActorCategory#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ActorCategory#getCodeActeur <em>Code Acteur</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ActorCategory#getCodeActeurs <em>Code Acteurs</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ActorCategory#getDescriptionActeur <em>Description Acteur</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ActorCategory#getActeursConcrets <em>Acteurs Concrets</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getActorCategory()
 * @model
 * @generated
 */
public interface ActorCategory extends ComplexParameter
{
  /**
   * Returns the value of the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifiant</em>' attribute.
   * @see #setIdentifiant(String)
   * @see org.xtext.example.process.process.ProcessPackage#getActorCategory_Identifiant()
   * @model
   * @generated
   */
  String getIdentifiant();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ActorCategory#getIdentifiant <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifiant</em>' attribute.
   * @see #getIdentifiant()
   * @generated
   */
  void setIdentifiant(String value);

  /**
   * Returns the value of the '<em><b>Code Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Acteur</em>' attribute.
   * @see #setCodeActeur(String)
   * @see org.xtext.example.process.process.ProcessPackage#getActorCategory_CodeActeur()
   * @model
   * @generated
   */
  String getCodeActeur();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ActorCategory#getCodeActeur <em>Code Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Acteur</em>' attribute.
   * @see #getCodeActeur()
   * @generated
   */
  void setCodeActeur(String value);

  /**
   * Returns the value of the '<em><b>Code Acteurs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Acteurs</em>' attribute list.
   * @see org.xtext.example.process.process.ProcessPackage#getActorCategory_CodeActeurs()
   * @model unique="false"
   * @generated
   */
  EList<String> getCodeActeurs();

  /**
   * Returns the value of the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description Acteur</em>' attribute.
   * @see #setDescriptionActeur(String)
   * @see org.xtext.example.process.process.ProcessPackage#getActorCategory_DescriptionActeur()
   * @model
   * @generated
   */
  String getDescriptionActeur();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ActorCategory#getDescriptionActeur <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description Acteur</em>' attribute.
   * @see #getDescriptionActeur()
   * @generated
   */
  void setDescriptionActeur(String value);

  /**
   * Returns the value of the '<em><b>Acteurs Concrets</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.ConcretActor}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acteurs Concrets</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getActorCategory_ActeursConcrets()
   * @model containment="true"
   * @generated
   */
  EList<ConcretActor> getActeursConcrets();

} // ActorCategory
