/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.ArrayAccess#getArray <em>Array</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ArrayAccess#getIndex <em>Index</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getArrayAccess()
 * @model
 * @generated
 */
public interface ArrayAccess extends Expression
{
  /**
   * Returns the value of the '<em><b>Array</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' reference.
   * @see #setArray(VariableDeclaration)
   * @see org.xtext.example.process.process.ProcessPackage#getArrayAccess_Array()
   * @model
   * @generated
   */
  VariableDeclaration getArray();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ArrayAccess#getArray <em>Array</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array</em>' reference.
   * @see #getArray()
   * @generated
   */
  void setArray(VariableDeclaration value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see org.xtext.example.process.process.ProcessPackage#getArrayAccess_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ArrayAccess#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

} // ArrayAccess
