/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concret Actor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.ConcretActor#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.ConcretActor#getDescriptionActeur <em>Description Acteur</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getConcretActor()
 * @model
 * @generated
 */
public interface ConcretActor extends ComplexParameter
{
  /**
   * Returns the value of the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifiant</em>' attribute.
   * @see #setIdentifiant(String)
   * @see org.xtext.example.process.process.ProcessPackage#getConcretActor_Identifiant()
   * @model
   * @generated
   */
  String getIdentifiant();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ConcretActor#getIdentifiant <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifiant</em>' attribute.
   * @see #getIdentifiant()
   * @generated
   */
  void setIdentifiant(String value);

  /**
   * Returns the value of the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description Acteur</em>' attribute.
   * @see #setDescriptionActeur(String)
   * @see org.xtext.example.process.process.ProcessPackage#getConcretActor_DescriptionActeur()
   * @model
   * @generated
   */
  String getDescriptionActeur();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.ConcretActor#getDescriptionActeur <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description Acteur</em>' attribute.
   * @see #getDescriptionActeur()
   * @generated
   */
  void setDescriptionActeur(String value);

} // ConcretActor
