/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.process.process.ProcessPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends Expression
{
} // Literal
