/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.Model#getProcessus <em>Processus</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Processus</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Process}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Processus</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getModel_Processus()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.example.process.process.Process> getProcessus();

} // Model
