/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.process.process.ProcessFactory
 * @model kind="package"
 * @generated
 */
public interface ProcessPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "process";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/process/Process";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "process";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ProcessPackage eINSTANCE = org.xtext.example.process.process.impl.ProcessPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ModelImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Processus</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROCESSUS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 7;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ComplexParameterImpl <em>Complex Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ComplexParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getComplexParameter()
   * @generated
   */
  int COMPLEX_PARAMETER = 13;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PARAMETER__VARIABLES = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Complex Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PARAMETER_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ProcessImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 1;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__VARIABLES = COMPLEX_PARAMETER__VARIABLES;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__IDENTIFIANT = COMPLEX_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__ENTREES = COMPLEX_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sorties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__SORTIES = COMPLEX_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Acteur Categories</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__ACTEUR_CATEGORIES = COMPLEX_PARAMETER_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Taches</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__TACHES = COMPLEX_PARAMETER_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = COMPLEX_PARAMETER_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ActorCategoryImpl <em>Actor Category</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ActorCategoryImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getActorCategory()
   * @generated
   */
  int ACTOR_CATEGORY = 2;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__VARIABLES = COMPLEX_PARAMETER__VARIABLES;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__IDENTIFIANT = COMPLEX_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Code Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__CODE_ACTEUR = COMPLEX_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Code Acteurs</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__CODE_ACTEURS = COMPLEX_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__DESCRIPTION_ACTEUR = COMPLEX_PARAMETER_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Acteurs Concrets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY__ACTEURS_CONCRETS = COMPLEX_PARAMETER_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Actor Category</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_CATEGORY_FEATURE_COUNT = COMPLEX_PARAMETER_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ConcretActorImpl <em>Concret Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ConcretActorImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getConcretActor()
   * @generated
   */
  int CONCRET_ACTOR = 3;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRET_ACTOR__VARIABLES = COMPLEX_PARAMETER__VARIABLES;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRET_ACTOR__IDENTIFIANT = COMPLEX_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRET_ACTOR__DESCRIPTION_ACTEUR = COMPLEX_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Concret Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCRET_ACTOR_FEATURE_COUNT = COMPLEX_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.TaskImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTask()
   * @generated
   */
  int TASK = 4;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.TaskSimpleImpl <em>Task Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.TaskSimpleImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTaskSimple()
   * @generated
   */
  int TASK_SIMPLE = 5;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE__VARIABLES = TASK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE__IDENTIFIANT = TASK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE__ENTREES = TASK_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Sorties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE__SORTIES = TASK_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE__DESCRIPTION_ACTEUR = TASK_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Task Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_SIMPLE_FEATURE_COUNT = TASK_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.TaskCompositeImpl <em>Task Composite</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.TaskCompositeImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTaskComposite()
   * @generated
   */
  int TASK_COMPOSITE = 6;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__VARIABLES = TASK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__IDENTIFIANT = TASK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Entrees</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__ENTREES = TASK_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Sorties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__SORTIES = TASK_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__DESCRIPTION_ACTEUR = TASK_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Taches</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE__TACHES = TASK_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Task Composite</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_COMPOSITE_FEATURE_COUNT = TASK_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.SimpleParameterImpl <em>Simple Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.SimpleParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getSimpleParameter()
   * @generated
   */
  int SIMPLE_PARAMETER = 8;

  /**
   * The number of structural features of the '<em>Simple Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_PARAMETER_FEATURE_COUNT = PARAMETER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.StringParameterImpl <em>String Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.StringParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getStringParameter()
   * @generated
   */
  int STRING_PARAMETER = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMETER__VALUE = SIMPLE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_PARAMETER_FEATURE_COUNT = SIMPLE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.IntParameterImpl <em>Int Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.IntParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getIntParameter()
   * @generated
   */
  int INT_PARAMETER = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_PARAMETER__VALUE = SIMPLE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_PARAMETER_FEATURE_COUNT = SIMPLE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.FloatParameterImpl <em>Float Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.FloatParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getFloatParameter()
   * @generated
   */
  int FLOAT_PARAMETER = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_PARAMETER__VALUE = SIMPLE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Float Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_PARAMETER_FEATURE_COUNT = SIMPLE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.BooleanParameterImpl <em>Boolean Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.BooleanParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getBooleanParameter()
   * @generated
   */
  int BOOLEAN_PARAMETER = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_PARAMETER__VALUE = SIMPLE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_PARAMETER_FEATURE_COUNT = SIMPLE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.CustumParameterImpl <em>Custum Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.CustumParameterImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getCustumParameter()
   * @generated
   */
  int CUSTUM_PARAMETER = 14;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER__VARIABLES = COMPLEX_PARAMETER__VARIABLES;

  /**
   * The feature id for the '<em><b>Nom Parametre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER__NOM_PARAMETRE = COMPLEX_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parametres Entree</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER__PARAMETRES_ENTREE = COMPLEX_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Parametres Sortie</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER__PARAMETRES_SORTIE = COMPLEX_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER__DESCRIPTION_ACTEUR = COMPLEX_PARAMETER_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Custum Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTUM_PARAMETER_FEATURE_COUNT = COMPLEX_PARAMETER_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.VariableDeclarationImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__TYPE = SIMPLE_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__IDENTIFIANT = SIMPLE_PARAMETER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = SIMPLE_PARAMETER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = SIMPLE_PARAMETER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ExpressionImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 16;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.LiteralImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 17;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.StringLiteralImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.IntLiteralImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.FloatLiteralImpl <em>Float Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.FloatLiteralImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getFloatLiteral()
   * @generated
   */
  int FLOAT_LITERAL = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Float Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOAT_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.BooleanLiteralImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getBooleanLiteral()
   * @generated
   */
  int BOOLEAN_LITERAL = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL__VALUE = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.VariableReferenceImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getVariableReference()
   * @generated
   */
  int VARIABLE_REFERENCE = 22;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE__VARIABLE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.process.process.impl.ArrayAccessImpl <em>Array Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.process.process.impl.ArrayAccessImpl
   * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getArrayAccess()
   * @generated
   */
  int ARRAY_ACCESS = 23;

  /**
   * The feature id for the '<em><b>Array</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ACCESS__ARRAY = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ACCESS__INDEX = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Array Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ACCESS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.process.process.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.Model#getProcessus <em>Processus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Processus</em>'.
   * @see org.xtext.example.process.process.Model#getProcessus()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Processus();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see org.xtext.example.process.process.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.Process#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.Process#getIdentifiant()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Identifiant();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.Process#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrees</em>'.
   * @see org.xtext.example.process.process.Process#getEntrees()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.Process#getSorties <em>Sorties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sorties</em>'.
   * @see org.xtext.example.process.process.Process#getSorties()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Sorties();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.Process#getActeurCategories <em>Acteur Categories</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Acteur Categories</em>'.
   * @see org.xtext.example.process.process.Process#getActeurCategories()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_ActeurCategories();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.Process#getTaches <em>Taches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Taches</em>'.
   * @see org.xtext.example.process.process.Process#getTaches()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Taches();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.ActorCategory <em>Actor Category</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor Category</em>'.
   * @see org.xtext.example.process.process.ActorCategory
   * @generated
   */
  EClass getActorCategory();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ActorCategory#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.ActorCategory#getIdentifiant()
   * @see #getActorCategory()
   * @generated
   */
  EAttribute getActorCategory_Identifiant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ActorCategory#getCodeActeur <em>Code Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code Acteur</em>'.
   * @see org.xtext.example.process.process.ActorCategory#getCodeActeur()
   * @see #getActorCategory()
   * @generated
   */
  EAttribute getActorCategory_CodeActeur();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.process.process.ActorCategory#getCodeActeurs <em>Code Acteurs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Code Acteurs</em>'.
   * @see org.xtext.example.process.process.ActorCategory#getCodeActeurs()
   * @see #getActorCategory()
   * @generated
   */
  EAttribute getActorCategory_CodeActeurs();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ActorCategory#getDescriptionActeur <em>Description Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description Acteur</em>'.
   * @see org.xtext.example.process.process.ActorCategory#getDescriptionActeur()
   * @see #getActorCategory()
   * @generated
   */
  EAttribute getActorCategory_DescriptionActeur();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.ActorCategory#getActeursConcrets <em>Acteurs Concrets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Acteurs Concrets</em>'.
   * @see org.xtext.example.process.process.ActorCategory#getActeursConcrets()
   * @see #getActorCategory()
   * @generated
   */
  EReference getActorCategory_ActeursConcrets();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.ConcretActor <em>Concret Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Concret Actor</em>'.
   * @see org.xtext.example.process.process.ConcretActor
   * @generated
   */
  EClass getConcretActor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ConcretActor#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.ConcretActor#getIdentifiant()
   * @see #getConcretActor()
   * @generated
   */
  EAttribute getConcretActor_Identifiant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ConcretActor#getDescriptionActeur <em>Description Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description Acteur</em>'.
   * @see org.xtext.example.process.process.ConcretActor#getDescriptionActeur()
   * @see #getConcretActor()
   * @generated
   */
  EAttribute getConcretActor_DescriptionActeur();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.example.process.process.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.TaskSimple <em>Task Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Simple</em>'.
   * @see org.xtext.example.process.process.TaskSimple
   * @generated
   */
  EClass getTaskSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.TaskSimple#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.TaskSimple#getIdentifiant()
   * @see #getTaskSimple()
   * @generated
   */
  EAttribute getTaskSimple_Identifiant();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.TaskSimple#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrees</em>'.
   * @see org.xtext.example.process.process.TaskSimple#getEntrees()
   * @see #getTaskSimple()
   * @generated
   */
  EReference getTaskSimple_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.TaskSimple#getSorties <em>Sorties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sorties</em>'.
   * @see org.xtext.example.process.process.TaskSimple#getSorties()
   * @see #getTaskSimple()
   * @generated
   */
  EReference getTaskSimple_Sorties();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.TaskSimple#getDescriptionActeur <em>Description Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description Acteur</em>'.
   * @see org.xtext.example.process.process.TaskSimple#getDescriptionActeur()
   * @see #getTaskSimple()
   * @generated
   */
  EAttribute getTaskSimple_DescriptionActeur();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.TaskComposite <em>Task Composite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Composite</em>'.
   * @see org.xtext.example.process.process.TaskComposite
   * @generated
   */
  EClass getTaskComposite();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.TaskComposite#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.TaskComposite#getIdentifiant()
   * @see #getTaskComposite()
   * @generated
   */
  EAttribute getTaskComposite_Identifiant();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.TaskComposite#getEntrees <em>Entrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entrees</em>'.
   * @see org.xtext.example.process.process.TaskComposite#getEntrees()
   * @see #getTaskComposite()
   * @generated
   */
  EReference getTaskComposite_Entrees();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.TaskComposite#getSorties <em>Sorties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sorties</em>'.
   * @see org.xtext.example.process.process.TaskComposite#getSorties()
   * @see #getTaskComposite()
   * @generated
   */
  EReference getTaskComposite_Sorties();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.TaskComposite#getDescriptionActeur <em>Description Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description Acteur</em>'.
   * @see org.xtext.example.process.process.TaskComposite#getDescriptionActeur()
   * @see #getTaskComposite()
   * @generated
   */
  EAttribute getTaskComposite_DescriptionActeur();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.TaskComposite#getTaches <em>Taches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Taches</em>'.
   * @see org.xtext.example.process.process.TaskComposite#getTaches()
   * @see #getTaskComposite()
   * @generated
   */
  EReference getTaskComposite_Taches();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.example.process.process.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.SimpleParameter <em>Simple Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Parameter</em>'.
   * @see org.xtext.example.process.process.SimpleParameter
   * @generated
   */
  EClass getSimpleParameter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.StringParameter <em>String Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Parameter</em>'.
   * @see org.xtext.example.process.process.StringParameter
   * @generated
   */
  EClass getStringParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.StringParameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.StringParameter#getValue()
   * @see #getStringParameter()
   * @generated
   */
  EAttribute getStringParameter_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.IntParameter <em>Int Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Parameter</em>'.
   * @see org.xtext.example.process.process.IntParameter
   * @generated
   */
  EClass getIntParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.IntParameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.IntParameter#getValue()
   * @see #getIntParameter()
   * @generated
   */
  EAttribute getIntParameter_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.FloatParameter <em>Float Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float Parameter</em>'.
   * @see org.xtext.example.process.process.FloatParameter
   * @generated
   */
  EClass getFloatParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.FloatParameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.FloatParameter#getValue()
   * @see #getFloatParameter()
   * @generated
   */
  EAttribute getFloatParameter_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.BooleanParameter <em>Boolean Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Parameter</em>'.
   * @see org.xtext.example.process.process.BooleanParameter
   * @generated
   */
  EClass getBooleanParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.BooleanParameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.BooleanParameter#getValue()
   * @see #getBooleanParameter()
   * @generated
   */
  EAttribute getBooleanParameter_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.ComplexParameter <em>Complex Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Parameter</em>'.
   * @see org.xtext.example.process.process.ComplexParameter
   * @generated
   */
  EClass getComplexParameter();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.ComplexParameter#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.xtext.example.process.process.ComplexParameter#getVariables()
   * @see #getComplexParameter()
   * @generated
   */
  EReference getComplexParameter_Variables();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.CustumParameter <em>Custum Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custum Parameter</em>'.
   * @see org.xtext.example.process.process.CustumParameter
   * @generated
   */
  EClass getCustumParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.CustumParameter#getNomParametre <em>Nom Parametre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom Parametre</em>'.
   * @see org.xtext.example.process.process.CustumParameter#getNomParametre()
   * @see #getCustumParameter()
   * @generated
   */
  EAttribute getCustumParameter_NomParametre();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.CustumParameter#getParametresEntree <em>Parametres Entree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres Entree</em>'.
   * @see org.xtext.example.process.process.CustumParameter#getParametresEntree()
   * @see #getCustumParameter()
   * @generated
   */
  EReference getCustumParameter_ParametresEntree();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.process.process.CustumParameter#getParametresSortie <em>Parametres Sortie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parametres Sortie</em>'.
   * @see org.xtext.example.process.process.CustumParameter#getParametresSortie()
   * @see #getCustumParameter()
   * @generated
   */
  EReference getCustumParameter_ParametresSortie();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.CustumParameter#getDescriptionActeur <em>Description Acteur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description Acteur</em>'.
   * @see org.xtext.example.process.process.CustumParameter#getDescriptionActeur()
   * @see #getCustumParameter()
   * @generated
   */
  EAttribute getCustumParameter_DescriptionActeur();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see org.xtext.example.process.process.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.VariableDeclaration#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.process.process.VariableDeclaration#getType()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.VariableDeclaration#getIdentifiant <em>Identifiant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Identifiant</em>'.
   * @see org.xtext.example.process.process.VariableDeclaration#getIdentifiant()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Identifiant();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.process.process.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.process.process.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EReference getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.process.process.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see org.xtext.example.process.process.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see org.xtext.example.process.process.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see org.xtext.example.process.process.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.IntLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.IntLiteral#getValue()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.FloatLiteral <em>Float Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Float Literal</em>'.
   * @see org.xtext.example.process.process.FloatLiteral
   * @generated
   */
  EClass getFloatLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.FloatLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.FloatLiteral#getValue()
   * @see #getFloatLiteral()
   * @generated
   */
  EAttribute getFloatLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.BooleanLiteral <em>Boolean Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Literal</em>'.
   * @see org.xtext.example.process.process.BooleanLiteral
   * @generated
   */
  EClass getBooleanLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.BooleanLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.process.process.BooleanLiteral#getValue()
   * @see #getBooleanLiteral()
   * @generated
   */
  EAttribute getBooleanLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.VariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Reference</em>'.
   * @see org.xtext.example.process.process.VariableReference
   * @generated
   */
  EClass getVariableReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.process.process.VariableReference#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see org.xtext.example.process.process.VariableReference#getVariable()
   * @see #getVariableReference()
   * @generated
   */
  EReference getVariableReference_Variable();

  /**
   * Returns the meta object for class '{@link org.xtext.example.process.process.ArrayAccess <em>Array Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Access</em>'.
   * @see org.xtext.example.process.process.ArrayAccess
   * @generated
   */
  EClass getArrayAccess();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.process.process.ArrayAccess#getArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Array</em>'.
   * @see org.xtext.example.process.process.ArrayAccess#getArray()
   * @see #getArrayAccess()
   * @generated
   */
  EReference getArrayAccess_Array();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.process.process.ArrayAccess#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Index</em>'.
   * @see org.xtext.example.process.process.ArrayAccess#getIndex()
   * @see #getArrayAccess()
   * @generated
   */
  EAttribute getArrayAccess_Index();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ProcessFactory getProcessFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ModelImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Processus</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROCESSUS = eINSTANCE.getModel_Processus();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ProcessImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__IDENTIFIANT = eINSTANCE.getProcess_Identifiant();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__ENTREES = eINSTANCE.getProcess_Entrees();

    /**
     * The meta object literal for the '<em><b>Sorties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__SORTIES = eINSTANCE.getProcess_Sorties();

    /**
     * The meta object literal for the '<em><b>Acteur Categories</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__ACTEUR_CATEGORIES = eINSTANCE.getProcess_ActeurCategories();

    /**
     * The meta object literal for the '<em><b>Taches</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__TACHES = eINSTANCE.getProcess_Taches();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ActorCategoryImpl <em>Actor Category</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ActorCategoryImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getActorCategory()
     * @generated
     */
    EClass ACTOR_CATEGORY = eINSTANCE.getActorCategory();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR_CATEGORY__IDENTIFIANT = eINSTANCE.getActorCategory_Identifiant();

    /**
     * The meta object literal for the '<em><b>Code Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR_CATEGORY__CODE_ACTEUR = eINSTANCE.getActorCategory_CodeActeur();

    /**
     * The meta object literal for the '<em><b>Code Acteurs</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR_CATEGORY__CODE_ACTEURS = eINSTANCE.getActorCategory_CodeActeurs();

    /**
     * The meta object literal for the '<em><b>Description Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR_CATEGORY__DESCRIPTION_ACTEUR = eINSTANCE.getActorCategory_DescriptionActeur();

    /**
     * The meta object literal for the '<em><b>Acteurs Concrets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTOR_CATEGORY__ACTEURS_CONCRETS = eINSTANCE.getActorCategory_ActeursConcrets();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ConcretActorImpl <em>Concret Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ConcretActorImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getConcretActor()
     * @generated
     */
    EClass CONCRET_ACTOR = eINSTANCE.getConcretActor();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCRET_ACTOR__IDENTIFIANT = eINSTANCE.getConcretActor_Identifiant();

    /**
     * The meta object literal for the '<em><b>Description Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCRET_ACTOR__DESCRIPTION_ACTEUR = eINSTANCE.getConcretActor_DescriptionActeur();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.TaskImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.TaskSimpleImpl <em>Task Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.TaskSimpleImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTaskSimple()
     * @generated
     */
    EClass TASK_SIMPLE = eINSTANCE.getTaskSimple();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_SIMPLE__IDENTIFIANT = eINSTANCE.getTaskSimple_Identifiant();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_SIMPLE__ENTREES = eINSTANCE.getTaskSimple_Entrees();

    /**
     * The meta object literal for the '<em><b>Sorties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_SIMPLE__SORTIES = eINSTANCE.getTaskSimple_Sorties();

    /**
     * The meta object literal for the '<em><b>Description Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_SIMPLE__DESCRIPTION_ACTEUR = eINSTANCE.getTaskSimple_DescriptionActeur();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.TaskCompositeImpl <em>Task Composite</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.TaskCompositeImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getTaskComposite()
     * @generated
     */
    EClass TASK_COMPOSITE = eINSTANCE.getTaskComposite();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_COMPOSITE__IDENTIFIANT = eINSTANCE.getTaskComposite_Identifiant();

    /**
     * The meta object literal for the '<em><b>Entrees</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_COMPOSITE__ENTREES = eINSTANCE.getTaskComposite_Entrees();

    /**
     * The meta object literal for the '<em><b>Sorties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_COMPOSITE__SORTIES = eINSTANCE.getTaskComposite_Sorties();

    /**
     * The meta object literal for the '<em><b>Description Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_COMPOSITE__DESCRIPTION_ACTEUR = eINSTANCE.getTaskComposite_DescriptionActeur();

    /**
     * The meta object literal for the '<em><b>Taches</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_COMPOSITE__TACHES = eINSTANCE.getTaskComposite_Taches();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.SimpleParameterImpl <em>Simple Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.SimpleParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getSimpleParameter()
     * @generated
     */
    EClass SIMPLE_PARAMETER = eINSTANCE.getSimpleParameter();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.StringParameterImpl <em>String Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.StringParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getStringParameter()
     * @generated
     */
    EClass STRING_PARAMETER = eINSTANCE.getStringParameter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_PARAMETER__VALUE = eINSTANCE.getStringParameter_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.IntParameterImpl <em>Int Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.IntParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getIntParameter()
     * @generated
     */
    EClass INT_PARAMETER = eINSTANCE.getIntParameter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_PARAMETER__VALUE = eINSTANCE.getIntParameter_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.FloatParameterImpl <em>Float Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.FloatParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getFloatParameter()
     * @generated
     */
    EClass FLOAT_PARAMETER = eINSTANCE.getFloatParameter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOAT_PARAMETER__VALUE = eINSTANCE.getFloatParameter_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.BooleanParameterImpl <em>Boolean Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.BooleanParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getBooleanParameter()
     * @generated
     */
    EClass BOOLEAN_PARAMETER = eINSTANCE.getBooleanParameter();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_PARAMETER__VALUE = eINSTANCE.getBooleanParameter_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ComplexParameterImpl <em>Complex Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ComplexParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getComplexParameter()
     * @generated
     */
    EClass COMPLEX_PARAMETER = eINSTANCE.getComplexParameter();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_PARAMETER__VARIABLES = eINSTANCE.getComplexParameter_Variables();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.CustumParameterImpl <em>Custum Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.CustumParameterImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getCustumParameter()
     * @generated
     */
    EClass CUSTUM_PARAMETER = eINSTANCE.getCustumParameter();

    /**
     * The meta object literal for the '<em><b>Nom Parametre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTUM_PARAMETER__NOM_PARAMETRE = eINSTANCE.getCustumParameter_NomParametre();

    /**
     * The meta object literal for the '<em><b>Parametres Entree</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTUM_PARAMETER__PARAMETRES_ENTREE = eINSTANCE.getCustumParameter_ParametresEntree();

    /**
     * The meta object literal for the '<em><b>Parametres Sortie</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTUM_PARAMETER__PARAMETRES_SORTIE = eINSTANCE.getCustumParameter_ParametresSortie();

    /**
     * The meta object literal for the '<em><b>Description Acteur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTUM_PARAMETER__DESCRIPTION_ACTEUR = eINSTANCE.getCustumParameter_DescriptionActeur();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.VariableDeclarationImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__TYPE = eINSTANCE.getVariableDeclaration_Type();

    /**
     * The meta object literal for the '<em><b>Identifiant</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__IDENTIFIANT = eINSTANCE.getVariableDeclaration_Identifiant();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ExpressionImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.LiteralImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.StringLiteralImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.IntLiteralImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getIntLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.FloatLiteralImpl <em>Float Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.FloatLiteralImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getFloatLiteral()
     * @generated
     */
    EClass FLOAT_LITERAL = eINSTANCE.getFloatLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOAT_LITERAL__VALUE = eINSTANCE.getFloatLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.BooleanLiteralImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getBooleanLiteral()
     * @generated
     */
    EClass BOOLEAN_LITERAL = eINSTANCE.getBooleanLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_LITERAL__VALUE = eINSTANCE.getBooleanLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.VariableReferenceImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getVariableReference()
     * @generated
     */
    EClass VARIABLE_REFERENCE = eINSTANCE.getVariableReference();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_REFERENCE__VARIABLE = eINSTANCE.getVariableReference_Variable();

    /**
     * The meta object literal for the '{@link org.xtext.example.process.process.impl.ArrayAccessImpl <em>Array Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.process.process.impl.ArrayAccessImpl
     * @see org.xtext.example.process.process.impl.ProcessPackageImpl#getArrayAccess()
     * @generated
     */
    EClass ARRAY_ACCESS = eINSTANCE.getArrayAccess();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_ACCESS__ARRAY = eINSTANCE.getArrayAccess_Array();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_ACCESS__INDEX = eINSTANCE.getArrayAccess_Index();

  }

} //ProcessPackage
