/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.Process#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.Process#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link org.xtext.example.process.process.Process#getSorties <em>Sorties</em>}</li>
 *   <li>{@link org.xtext.example.process.process.Process#getActeurCategories <em>Acteur Categories</em>}</li>
 *   <li>{@link org.xtext.example.process.process.Process#getTaches <em>Taches</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends ComplexParameter
{
  /**
   * Returns the value of the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifiant</em>' attribute.
   * @see #setIdentifiant(String)
   * @see org.xtext.example.process.process.ProcessPackage#getProcess_Identifiant()
   * @model
   * @generated
   */
  String getIdentifiant();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.Process#getIdentifiant <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifiant</em>' attribute.
   * @see #getIdentifiant()
   * @generated
   */
  void setIdentifiant(String value);

  /**
   * Returns the value of the '<em><b>Entrees</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrees</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getProcess_Entrees()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getEntrees();

  /**
   * Returns the value of the '<em><b>Sorties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sorties</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getProcess_Sorties()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getSorties();

  /**
   * Returns the value of the '<em><b>Acteur Categories</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.ActorCategory}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Acteur Categories</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getProcess_ActeurCategories()
   * @model containment="true"
   * @generated
   */
  EList<ActorCategory> getActeurCategories();

  /**
   * Returns the value of the '<em><b>Taches</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Taches</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getProcess_Taches()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTaches();

} // Process
