/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.process.process.ProcessPackage#getSimpleParameter()
 * @model
 * @generated
 */
public interface SimpleParameter extends Parameter
{
} // SimpleParameter
