/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Composite</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.TaskComposite#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.TaskComposite#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link org.xtext.example.process.process.TaskComposite#getSorties <em>Sorties</em>}</li>
 *   <li>{@link org.xtext.example.process.process.TaskComposite#getDescriptionActeur <em>Description Acteur</em>}</li>
 *   <li>{@link org.xtext.example.process.process.TaskComposite#getTaches <em>Taches</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite()
 * @model
 * @generated
 */
public interface TaskComposite extends Task, ComplexParameter
{
  /**
   * Returns the value of the '<em><b>Identifiant</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Identifiant</em>' attribute.
   * @see #setIdentifiant(String)
   * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite_Identifiant()
   * @model
   * @generated
   */
  String getIdentifiant();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.TaskComposite#getIdentifiant <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Identifiant</em>' attribute.
   * @see #getIdentifiant()
   * @generated
   */
  void setIdentifiant(String value);

  /**
   * Returns the value of the '<em><b>Entrees</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrees</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite_Entrees()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getEntrees();

  /**
   * Returns the value of the '<em><b>Sorties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sorties</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite_Sorties()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getSorties();

  /**
   * Returns the value of the '<em><b>Description Acteur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description Acteur</em>' attribute.
   * @see #setDescriptionActeur(String)
   * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite_DescriptionActeur()
   * @model
   * @generated
   */
  String getDescriptionActeur();

  /**
   * Sets the value of the '{@link org.xtext.example.process.process.TaskComposite#getDescriptionActeur <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description Acteur</em>' attribute.
   * @see #getDescriptionActeur()
   * @generated
   */
  void setDescriptionActeur(String value);

  /**
   * Returns the value of the '<em><b>Taches</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.process.process.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Taches</em>' containment reference list.
   * @see org.xtext.example.process.process.ProcessPackage#getTaskComposite_Taches()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTaches();

} // TaskComposite
