/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.process.parser.antlr.internal.InternalProcessParser;
import org.xtext.example.process.services.ProcessGrammarAccess;

public class ProcessParser extends AbstractAntlrParser {

	@Inject
	private ProcessGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProcessParser createParser(XtextTokenStream stream) {
		return new InternalProcessParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ProcessGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProcessGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
