/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.process.ui.internal.ProcessActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProcessExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ProcessActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ProcessActivator activator = ProcessActivator.getInstance();
		return activator != null ? activator.getInjector(ProcessActivator.ORG_XTEXT_EXAMPLE_PROCESS_PROCESS) : null;
	}

}
