/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.process.ui.internal.ProcessActivator;

public class ProcessUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProcessActivator.getInstance().getInjector("org.xtext.example.process.Process");
	}

}
