/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.process.process.ActorCategory;
import org.xtext.example.process.process.ConcretActor;
import org.xtext.example.process.process.ProcessPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Actor Category</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.impl.ActorCategoryImpl#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ActorCategoryImpl#getCodeActeur <em>Code Acteur</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ActorCategoryImpl#getCodeActeurs <em>Code Acteurs</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ActorCategoryImpl#getDescriptionActeur <em>Description Acteur</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ActorCategoryImpl#getActeursConcrets <em>Acteurs Concrets</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ActorCategoryImpl extends ComplexParameterImpl implements ActorCategory
{
  /**
   * The default value of the '{@link #getIdentifiant() <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifiant()
   * @generated
   * @ordered
   */
  protected static final String IDENTIFIANT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdentifiant() <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifiant()
   * @generated
   * @ordered
   */
  protected String identifiant = IDENTIFIANT_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeActeur() <em>Code Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeActeur()
   * @generated
   * @ordered
   */
  protected static final String CODE_ACTEUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeActeur() <em>Code Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeActeur()
   * @generated
   * @ordered
   */
  protected String codeActeur = CODE_ACTEUR_EDEFAULT;

  /**
   * The cached value of the '{@link #getCodeActeurs() <em>Code Acteurs</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeActeurs()
   * @generated
   * @ordered
   */
  protected EList<String> codeActeurs;

  /**
   * The default value of the '{@link #getDescriptionActeur() <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptionActeur()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_ACTEUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescriptionActeur() <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptionActeur()
   * @generated
   * @ordered
   */
  protected String descriptionActeur = DESCRIPTION_ACTEUR_EDEFAULT;

  /**
   * The cached value of the '{@link #getActeursConcrets() <em>Acteurs Concrets</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActeursConcrets()
   * @generated
   * @ordered
   */
  protected EList<ConcretActor> acteursConcrets;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActorCategoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProcessPackage.Literals.ACTOR_CATEGORY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIdentifiant()
  {
    return identifiant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIdentifiant(String newIdentifiant)
  {
    String oldIdentifiant = identifiant;
    identifiant = newIdentifiant;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.ACTOR_CATEGORY__IDENTIFIANT, oldIdentifiant, identifiant));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCodeActeur()
  {
    return codeActeur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCodeActeur(String newCodeActeur)
  {
    String oldCodeActeur = codeActeur;
    codeActeur = newCodeActeur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.ACTOR_CATEGORY__CODE_ACTEUR, oldCodeActeur, codeActeur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getCodeActeurs()
  {
    if (codeActeurs == null)
    {
      codeActeurs = new EDataTypeEList<String>(String.class, this, ProcessPackage.ACTOR_CATEGORY__CODE_ACTEURS);
    }
    return codeActeurs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescriptionActeur()
  {
    return descriptionActeur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescriptionActeur(String newDescriptionActeur)
  {
    String oldDescriptionActeur = descriptionActeur;
    descriptionActeur = newDescriptionActeur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.ACTOR_CATEGORY__DESCRIPTION_ACTEUR, oldDescriptionActeur, descriptionActeur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ConcretActor> getActeursConcrets()
  {
    if (acteursConcrets == null)
    {
      acteursConcrets = new EObjectContainmentEList<ConcretActor>(ConcretActor.class, this, ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS);
    }
    return acteursConcrets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS:
        return ((InternalEList<?>)getActeursConcrets()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProcessPackage.ACTOR_CATEGORY__IDENTIFIANT:
        return getIdentifiant();
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEUR:
        return getCodeActeur();
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEURS:
        return getCodeActeurs();
      case ProcessPackage.ACTOR_CATEGORY__DESCRIPTION_ACTEUR:
        return getDescriptionActeur();
      case ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS:
        return getActeursConcrets();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProcessPackage.ACTOR_CATEGORY__IDENTIFIANT:
        setIdentifiant((String)newValue);
        return;
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEUR:
        setCodeActeur((String)newValue);
        return;
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEURS:
        getCodeActeurs().clear();
        getCodeActeurs().addAll((Collection<? extends String>)newValue);
        return;
      case ProcessPackage.ACTOR_CATEGORY__DESCRIPTION_ACTEUR:
        setDescriptionActeur((String)newValue);
        return;
      case ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS:
        getActeursConcrets().clear();
        getActeursConcrets().addAll((Collection<? extends ConcretActor>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.ACTOR_CATEGORY__IDENTIFIANT:
        setIdentifiant(IDENTIFIANT_EDEFAULT);
        return;
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEUR:
        setCodeActeur(CODE_ACTEUR_EDEFAULT);
        return;
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEURS:
        getCodeActeurs().clear();
        return;
      case ProcessPackage.ACTOR_CATEGORY__DESCRIPTION_ACTEUR:
        setDescriptionActeur(DESCRIPTION_ACTEUR_EDEFAULT);
        return;
      case ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS:
        getActeursConcrets().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.ACTOR_CATEGORY__IDENTIFIANT:
        return IDENTIFIANT_EDEFAULT == null ? identifiant != null : !IDENTIFIANT_EDEFAULT.equals(identifiant);
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEUR:
        return CODE_ACTEUR_EDEFAULT == null ? codeActeur != null : !CODE_ACTEUR_EDEFAULT.equals(codeActeur);
      case ProcessPackage.ACTOR_CATEGORY__CODE_ACTEURS:
        return codeActeurs != null && !codeActeurs.isEmpty();
      case ProcessPackage.ACTOR_CATEGORY__DESCRIPTION_ACTEUR:
        return DESCRIPTION_ACTEUR_EDEFAULT == null ? descriptionActeur != null : !DESCRIPTION_ACTEUR_EDEFAULT.equals(descriptionActeur);
      case ProcessPackage.ACTOR_CATEGORY__ACTEURS_CONCRETS:
        return acteursConcrets != null && !acteursConcrets.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (identifiant: ");
    result.append(identifiant);
    result.append(", codeActeur: ");
    result.append(codeActeur);
    result.append(", codeActeurs: ");
    result.append(codeActeurs);
    result.append(", descriptionActeur: ");
    result.append(descriptionActeur);
    result.append(')');
    return result.toString();
  }

} //ActorCategoryImpl
