/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.process.process.CustumParameter;
import org.xtext.example.process.process.Parameter;
import org.xtext.example.process.process.ProcessPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Custum Parameter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.impl.CustumParameterImpl#getNomParametre <em>Nom Parametre</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.CustumParameterImpl#getParametresEntree <em>Parametres Entree</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.CustumParameterImpl#getParametresSortie <em>Parametres Sortie</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.CustumParameterImpl#getDescriptionActeur <em>Description Acteur</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustumParameterImpl extends ComplexParameterImpl implements CustumParameter
{
  /**
   * The default value of the '{@link #getNomParametre() <em>Nom Parametre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomParametre()
   * @generated
   * @ordered
   */
  protected static final String NOM_PARAMETRE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNomParametre() <em>Nom Parametre</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNomParametre()
   * @generated
   * @ordered
   */
  protected String nomParametre = NOM_PARAMETRE_EDEFAULT;

  /**
   * The cached value of the '{@link #getParametresEntree() <em>Parametres Entree</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametresEntree()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parametresEntree;

  /**
   * The cached value of the '{@link #getParametresSortie() <em>Parametres Sortie</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametresSortie()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parametresSortie;

  /**
   * The default value of the '{@link #getDescriptionActeur() <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptionActeur()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_ACTEUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescriptionActeur() <em>Description Acteur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptionActeur()
   * @generated
   * @ordered
   */
  protected String descriptionActeur = DESCRIPTION_ACTEUR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustumParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProcessPackage.Literals.CUSTUM_PARAMETER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNomParametre()
  {
    return nomParametre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNomParametre(String newNomParametre)
  {
    String oldNomParametre = nomParametre;
    nomParametre = newNomParametre;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.CUSTUM_PARAMETER__NOM_PARAMETRE, oldNomParametre, nomParametre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getParametresEntree()
  {
    if (parametresEntree == null)
    {
      parametresEntree = new EObjectContainmentEList<Parameter>(Parameter.class, this, ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE);
    }
    return parametresEntree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getParametresSortie()
  {
    if (parametresSortie == null)
    {
      parametresSortie = new EObjectContainmentEList<Parameter>(Parameter.class, this, ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE);
    }
    return parametresSortie;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescriptionActeur()
  {
    return descriptionActeur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescriptionActeur(String newDescriptionActeur)
  {
    String oldDescriptionActeur = descriptionActeur;
    descriptionActeur = newDescriptionActeur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.CUSTUM_PARAMETER__DESCRIPTION_ACTEUR, oldDescriptionActeur, descriptionActeur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE:
        return ((InternalEList<?>)getParametresEntree()).basicRemove(otherEnd, msgs);
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE:
        return ((InternalEList<?>)getParametresSortie()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProcessPackage.CUSTUM_PARAMETER__NOM_PARAMETRE:
        return getNomParametre();
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE:
        return getParametresEntree();
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE:
        return getParametresSortie();
      case ProcessPackage.CUSTUM_PARAMETER__DESCRIPTION_ACTEUR:
        return getDescriptionActeur();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProcessPackage.CUSTUM_PARAMETER__NOM_PARAMETRE:
        setNomParametre((String)newValue);
        return;
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE:
        getParametresEntree().clear();
        getParametresEntree().addAll((Collection<? extends Parameter>)newValue);
        return;
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE:
        getParametresSortie().clear();
        getParametresSortie().addAll((Collection<? extends Parameter>)newValue);
        return;
      case ProcessPackage.CUSTUM_PARAMETER__DESCRIPTION_ACTEUR:
        setDescriptionActeur((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.CUSTUM_PARAMETER__NOM_PARAMETRE:
        setNomParametre(NOM_PARAMETRE_EDEFAULT);
        return;
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE:
        getParametresEntree().clear();
        return;
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE:
        getParametresSortie().clear();
        return;
      case ProcessPackage.CUSTUM_PARAMETER__DESCRIPTION_ACTEUR:
        setDescriptionActeur(DESCRIPTION_ACTEUR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.CUSTUM_PARAMETER__NOM_PARAMETRE:
        return NOM_PARAMETRE_EDEFAULT == null ? nomParametre != null : !NOM_PARAMETRE_EDEFAULT.equals(nomParametre);
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_ENTREE:
        return parametresEntree != null && !parametresEntree.isEmpty();
      case ProcessPackage.CUSTUM_PARAMETER__PARAMETRES_SORTIE:
        return parametresSortie != null && !parametresSortie.isEmpty();
      case ProcessPackage.CUSTUM_PARAMETER__DESCRIPTION_ACTEUR:
        return DESCRIPTION_ACTEUR_EDEFAULT == null ? descriptionActeur != null : !DESCRIPTION_ACTEUR_EDEFAULT.equals(descriptionActeur);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nomParametre: ");
    result.append(nomParametre);
    result.append(", descriptionActeur: ");
    result.append(descriptionActeur);
    result.append(')');
    return result.toString();
  }

} //CustumParameterImpl
