/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.process.process.ActorCategory;
import org.xtext.example.process.process.Parameter;
import org.xtext.example.process.process.ProcessPackage;
import org.xtext.example.process.process.Task;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.process.process.impl.ProcessImpl#getIdentifiant <em>Identifiant</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ProcessImpl#getEntrees <em>Entrees</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ProcessImpl#getSorties <em>Sorties</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ProcessImpl#getActeurCategories <em>Acteur Categories</em>}</li>
 *   <li>{@link org.xtext.example.process.process.impl.ProcessImpl#getTaches <em>Taches</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessImpl extends ComplexParameterImpl implements org.xtext.example.process.process.Process
{
  /**
   * The default value of the '{@link #getIdentifiant() <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifiant()
   * @generated
   * @ordered
   */
  protected static final String IDENTIFIANT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIdentifiant() <em>Identifiant</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdentifiant()
   * @generated
   * @ordered
   */
  protected String identifiant = IDENTIFIANT_EDEFAULT;

  /**
   * The cached value of the '{@link #getEntrees() <em>Entrees</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntrees()
   * @generated
   * @ordered
   */
  protected EList<Parameter> entrees;

  /**
   * The cached value of the '{@link #getSorties() <em>Sorties</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSorties()
   * @generated
   * @ordered
   */
  protected EList<Parameter> sorties;

  /**
   * The cached value of the '{@link #getActeurCategories() <em>Acteur Categories</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActeurCategories()
   * @generated
   * @ordered
   */
  protected EList<ActorCategory> acteurCategories;

  /**
   * The cached value of the '{@link #getTaches() <em>Taches</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTaches()
   * @generated
   * @ordered
   */
  protected EList<Task> taches;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProcessPackage.Literals.PROCESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getIdentifiant()
  {
    return identifiant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIdentifiant(String newIdentifiant)
  {
    String oldIdentifiant = identifiant;
    identifiant = newIdentifiant;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ProcessPackage.PROCESS__IDENTIFIANT, oldIdentifiant, identifiant));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getEntrees()
  {
    if (entrees == null)
    {
      entrees = new EObjectContainmentEList<Parameter>(Parameter.class, this, ProcessPackage.PROCESS__ENTREES);
    }
    return entrees;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Parameter> getSorties()
  {
    if (sorties == null)
    {
      sorties = new EObjectContainmentEList<Parameter>(Parameter.class, this, ProcessPackage.PROCESS__SORTIES);
    }
    return sorties;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ActorCategory> getActeurCategories()
  {
    if (acteurCategories == null)
    {
      acteurCategories = new EObjectContainmentEList<ActorCategory>(ActorCategory.class, this, ProcessPackage.PROCESS__ACTEUR_CATEGORIES);
    }
    return acteurCategories;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Task> getTaches()
  {
    if (taches == null)
    {
      taches = new EObjectContainmentEList<Task>(Task.class, this, ProcessPackage.PROCESS__TACHES);
    }
    return taches;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ProcessPackage.PROCESS__ENTREES:
        return ((InternalEList<?>)getEntrees()).basicRemove(otherEnd, msgs);
      case ProcessPackage.PROCESS__SORTIES:
        return ((InternalEList<?>)getSorties()).basicRemove(otherEnd, msgs);
      case ProcessPackage.PROCESS__ACTEUR_CATEGORIES:
        return ((InternalEList<?>)getActeurCategories()).basicRemove(otherEnd, msgs);
      case ProcessPackage.PROCESS__TACHES:
        return ((InternalEList<?>)getTaches()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ProcessPackage.PROCESS__IDENTIFIANT:
        return getIdentifiant();
      case ProcessPackage.PROCESS__ENTREES:
        return getEntrees();
      case ProcessPackage.PROCESS__SORTIES:
        return getSorties();
      case ProcessPackage.PROCESS__ACTEUR_CATEGORIES:
        return getActeurCategories();
      case ProcessPackage.PROCESS__TACHES:
        return getTaches();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ProcessPackage.PROCESS__IDENTIFIANT:
        setIdentifiant((String)newValue);
        return;
      case ProcessPackage.PROCESS__ENTREES:
        getEntrees().clear();
        getEntrees().addAll((Collection<? extends Parameter>)newValue);
        return;
      case ProcessPackage.PROCESS__SORTIES:
        getSorties().clear();
        getSorties().addAll((Collection<? extends Parameter>)newValue);
        return;
      case ProcessPackage.PROCESS__ACTEUR_CATEGORIES:
        getActeurCategories().clear();
        getActeurCategories().addAll((Collection<? extends ActorCategory>)newValue);
        return;
      case ProcessPackage.PROCESS__TACHES:
        getTaches().clear();
        getTaches().addAll((Collection<? extends Task>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.PROCESS__IDENTIFIANT:
        setIdentifiant(IDENTIFIANT_EDEFAULT);
        return;
      case ProcessPackage.PROCESS__ENTREES:
        getEntrees().clear();
        return;
      case ProcessPackage.PROCESS__SORTIES:
        getSorties().clear();
        return;
      case ProcessPackage.PROCESS__ACTEUR_CATEGORIES:
        getActeurCategories().clear();
        return;
      case ProcessPackage.PROCESS__TACHES:
        getTaches().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ProcessPackage.PROCESS__IDENTIFIANT:
        return IDENTIFIANT_EDEFAULT == null ? identifiant != null : !IDENTIFIANT_EDEFAULT.equals(identifiant);
      case ProcessPackage.PROCESS__ENTREES:
        return entrees != null && !entrees.isEmpty();
      case ProcessPackage.PROCESS__SORTIES:
        return sorties != null && !sorties.isEmpty();
      case ProcessPackage.PROCESS__ACTEUR_CATEGORIES:
        return acteurCategories != null && !acteurCategories.isEmpty();
      case ProcessPackage.PROCESS__TACHES:
        return taches != null && !taches.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (identifiant: ");
    result.append(identifiant);
    result.append(')');
    return result.toString();
  }

} //ProcessImpl
