/**
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.process.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.process.process.ProcessPackage;
import org.xtext.example.process.process.SimpleParameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleParameterImpl extends ParameterImpl implements SimpleParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProcessPackage.Literals.SIMPLE_PARAMETER;
  }

} //SimpleParameterImpl
