/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProcessUiModule extends AbstractProcessUiModule {

	public ProcessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
