/*
 * generated by Xtext 2.35.0
 */
package org.xtext.example.process;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProcessStandaloneSetup extends ProcessStandaloneSetupGenerated {

	public static void doSetup() {
		new ProcessStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
